# Generated by Django 3.2.7 on 2021-09-18 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_remove_profile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='compensation',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
