# Generated by Django 3.2.7 on 2021-09-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_rename_year_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='numberhired',
            new_name='number_hired_with_role',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='year_of_hiring',
        ),
    ]
