# Generated by Django 3.2.7 on 2021-09-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_rename_compensation_post_compensation_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='additional',
            new_name='Additional_Topics',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='Company_Logo',
        ),
    ]
