# Generated by Django 3.2.7 on 2021-09-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_auto_20210919_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='Interview_Rounds_with_detailed_description',
        ),
    ]
