# Generated by Django 3.2.7 on 2021-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_rename_body_post_interview_rounds_with_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year_of_hiring',
            field=models.CharField(default='2019', max_length=255),
        ),
    ]
