# Generated by Django 3.2.7 on 2021-09-19 08:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0021_alter_post_year_of_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Additional_Topics',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
