# Generated by Django 3.2.7 on 2021-09-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0024_alter_post_additional_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
