# Generated by Django 3.2.7 on 2021-09-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0025_remove_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram_url',
            new_name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
    ]
