# Generated by Django 3.2.7 on 2021-09-22 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0026_auto_20210920_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
