# Generated by Django 3.2.7 on 2021-09-23 08:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0027_post_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_Name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('Company_Logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('hiring_type', models.CharField(max_length=255)),
                ('Interview_Rounds_with_detailed_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('year_of_hiring', models.CharField(default='2019', max_length=255)),
                ('number_hired_with_role', models.CharField(max_length=255)),
                ('compensation_Details', models.CharField(max_length=255)),
                ('Additional_Topics', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes_int', models.ManyToManyField(related_name='blog_posts_int', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
