# Generated by Django 3.2.7 on 2021-09-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0028_postint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
