# Generated by Django 3.2.7 on 2021-09-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0029_categoryint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postint',
            name='likes_int',
        ),
    ]
