# Generated by Django 3.2.7 on 2021-09-23 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0030_remove_postint_likes_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='postint',
            name='likes_int',
            field=models.ManyToManyField(related_name='blog_posts_int', to=settings.AUTH_USER_MODEL),
        ),
    ]
