# Generated by Django 3.2.7 on 2021-09-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0031_postint_likes_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('postint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsint', to='theblog.postint')),
            ],
        ),
    ]
