# Generated by Django 3.2.7 on 2021-10-04 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0032_commentint'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_comment',
            field=models.ManyToManyField(related_name='blog_posts_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
