# Generated by Django 3.2.7 on 2021-10-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0033_comment_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_comment',
        ),
    ]
